common/coin_support/eth.c
common/coin_support/eth.h
src/level_four/core/tasks/send_transaction_tasks_eth.c

Currently the gas price is assumed to be of integer value in Gwei. If the value is non-integer, then the current method of calculation leads to truncation of values when converted to Gwei
Fixes https://app.clickup.com/t/37308523/CHI-2003

Fix the fee calculation for non-integer Gwei gasPrice

---

common/libraries/util/pow_utilities.c

Fixes https://app.clickup.com/t/37308523/CHI-2045
The time calculation has been upper bounded to value of 99 seconds if the time overflows a 32-bit storage. Changing the upper bound to UINT32_MAX and using 64-bit storage for calculation.

Correct time calculation for overflow condition

---

src/level_four/core/controller/initial_verify_card_controller.c
src/level_four/core/controller/verify_card_controller.c

Fixes https://app.clickup.com/t/37308523/CHI-2044
The comm_process_complete will clear the cmdState to NONE which will essentially result into the device's last response being discarded. As a result the desktop never receives the device's response.

Remove unnecessary calls to comm_process_complete 

---

common/coin_support/avalanche.h

Fixes https://app.clickup.com/t/37308523/CHI-2128

fix: Rename Avalanche network name to Avalanche C-Chain

---

.github/workflows/build.yml

Every build generated on a tag will now publish a draft release under GitHub releases section.
The draft release will contain
1. The unsigned firmware binaries
2. The sha256 checksum of the firmware binaries
3. Link to the changelog

feat (ci): Publish draft release post build pipeline

---

src/level_four/core/tasks/receive_transaction_tasks_eth.c

Ethereum default address of the form `0xe688b84b23f322a994a53dbf8e15fa82cdb71127` is of 43 byte including the `null` character.
Also, harmony's bech32 addresses also result into 43 bytes including `null` character.
So size 43 fits both the types of addresses.

Use exact buffer size for ethereum addresses

---

common/coin_support/coin_utils.c
common/coin_support/coin_utils.h
common/coin_support/near.c
common/coin_support/solana.c
src/controller_main.c
src/level_four/core/controller/receive_transaction_controller.c
src/level_four/core/controller/receive_transaction_controller_eth.c
src/level_four/core/controller/receive_transaction_controller_near.c
src/level_four/core/controller/receive_transaction_controller_solana.c

Currently the level four of HD Key path variable is named `chain_index` which is wrong as the level four is known as `Change index`. So the relevant name for all such variable is `change_index`.

refactor: Rename change index variable from chain to change

---

common/interfaces/flash_interface/flash_api.c

Fixes comparison of keys installed on device: zero-ise key buffer before reading back from flash memory

zero-ise buffer before reading back io protection key and ext keys

---

src/main.c
utilities/cmake/simulator.cmake

1. Simulator binary linker changes
The 'release' variant of simulator binary is having problem with current linker options of math library. The cmake method `target_link_options` does not allow linking of static libraries. Now using cmake method `target_link_libraries` to link the math library.
2. Function definition change
The simulator binary for Windows platform uses `SDL_main` in place of `main` function as entry point. But the simulator binary on unix platform accepts the `main` function as entry point. So wrapping the macro only for Windows platform.

fix (simulator): Correct linker options and main definition

---

.github/workflows/build-test.yml

With this workflow, the idea is that every PR goes through a build-test step to ensure all the binaries are building successfully.
Builds that will be attempted:
1. Release and dev build of target binaries of Main and Initial firmwares
2. Release and dev build of simulator binaries of Main and Initial firmwares

feat (ci): Add build test on PRs

---

utilities/ci/test-commit-msg.sh

The commit msg check is failing wrongly. Ref: https://github.com/Cypherock/x1_wallet_firmware/actions/runs/4618412812/jobs/8165835615.
The current list of commit is generated out of both the work and base branches. We only need commits from the work branch that will be added to base branch. Ref: https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#double_dot

Correct git commit list for checking commit message

---

utilities/cmake/version.cmake

The current call to execute_process uses `bash` to execute the test command for checking dirtiness of the git worktree. It takes a long time about a few seconds when executed on windows in git-bash. Replacing with `sh` changes the behaviour and it takes under a second (as expected). This is mostly observed on systems where WSL is enabled in which case, running an instance of bash takes longer.

fix (build): Reduce time to generate git commit-id

---

common/interfaces/user_interface/ui_address.c
common/interfaces/user_interface/ui_confirmation.c
common/interfaces/user_interface/ui_delay.c
common/interfaces/user_interface/ui_delay.h
common/interfaces/user_interface/ui_input_mnemonics.c
common/interfaces/user_interface/ui_input_text.c
common/interfaces/user_interface/ui_input_text.h
common/interfaces/user_interface/ui_list.c
common/interfaces/user_interface/ui_menu.c
common/interfaces/user_interface/ui_message.c
common/interfaces/user_interface/ui_multi_instruction.c
common/interfaces/user_interface/ui_scroll_page.c

This PR adds call to function `lv_obj_clean` from all UI components, to ensure all objects of previously rendered screens are cleaned.
Added handling of event `LV_EVENT_DELETE` in all UI callbacks, which will be responsible for deleting the objects. 
1. By having this fix in place, application can freely render UI components one after the other without having to worry about destructing and previous component
2. For `ui_input_text` this change does not seem to be compatible and therefore, for that particular component, will will have to call the destructor manually

refactor(ui): Call ui destructor from `lv_event_delete` case

---

CMakeLists.txt
common/proto-options/btc/core.options
common/proto-options/btc/error.options
common/proto-options/btc/get_public_key.options
common/proto-options/btc/get_xpubs.options
common/proto-options/btc/sign_txn.options
common/proto-options/common.options
common/proto-options/core.options
common/proto-options/error.options
common/proto-options/evm/common.options
common/proto-options/evm/core.options
common/proto-options/evm/get_public_keys.options
common/proto-options/evm/sign_msg.options
common/proto-options/evm/sign_txn.options
common/proto-options/manager/auth_card.options
common/proto-options/manager/auth_device.options
common/proto-options/manager/core.options
common/proto-options/manager/get_device_info.options
common/proto-options/manager/get_logs.options
common/proto-options/manager/get_wallets.options
common/proto-options/manager/train_user.options
utilities/proto/gen-options.sh
utilities/proto/gen_options.sh
utilities/proto/generate-protob.sh

To integrate some protobuf structures in our project, we need to configure options for the nanopb compiler. 
This PR generates the options files for each proto file and configures nanopb compiler to use these options files
Of course, these options file will be modified later as per usage.

feat (build): Add bash script to auto-generate options file

---

common/core/status_api.c
common/interfaces/desktop_app_interface/usb_api.c

Fixes
The current behavior is not consistent with the expectations of the API. Because, if the application sends 0-sized messages, the current API will do an early exit which leads to unserved USB events. This can cause issues in the application state and hence out of sync with the host application.

Fix core apis: usb and application status

---

.vscode/settings.json

VS code's cmake extension omits FIRMWARE_TYPE as an argument when compiling, this is a fix.

chore(build): Fix vscode cmake issue for configure

---

common/interfaces/user_interface/ui_input_mnemonics.c
src/level_four/core/controller/add_coin_controller.c
src/level_four/core/controller/initial_device_provision_contoller.c
src/level_three/add_wallet/controller/controller_arbitrary_data.c
src/level_three/add_wallet/controller/controller_restore_wallet.c
src/level_three/add_wallet/tasks/tasks_new_wallet.c

The import of static list of string array unneccesararily bloats the binary size. Replace the import with provided api function. This reduces the size of .text section from 547108 bytes to 530836 bytes (on windows build environment). A difference of 16272 bytes (~16 kB).

fix (core): Optimize usage of bip39 wordlist

---

apps/manager_app/card_training.c
src/card_operations/check_pairing.c

The buzzer should make a sound in the success case only. Abort from the host should not trigger the buzzer. Also, card operation abort errors are now handled globally hence its handling is being removed. Update the card training state to the flash.

fix: Card training buzzer and state correction

---

apps/btc_app/get_xpub.c
apps/manager_app/get_logs.c

All the screens conveying background processing/computation (eg. "Processing...", "Sending logs...", etc. had a possibility of showing glitch behaviour if the processing time is very small. The recent proting of the flows dropped this subtle requirement.

fix (app): Add hard delay screen at flow completion

---

apps/btc_app/get_xpub.c
apps/manager_app/device_authentication.c
apps/manager_app/get_logs.c
common/core/ui_core_confirm.c
common/core/ui_core_confirm.h

The current implementation for `core_user_confirmation` only covers the specific use-case for confirm_scr_init UI. Other screen types can also generate the same events and also the same handling. Adding support for those UI screens will consolidate duplicated logic from the application.

refactor (core): Add screen type to core_user_confirmation

---

common/interfaces/user_interface/ui_address.c
common/interfaces/user_interface/ui_confirmation.c
common/interfaces/user_interface/ui_input_mnemonics.c
common/interfaces/user_interface/ui_list.c
common/interfaces/user_interface/ui_menu.c
common/interfaces/user_interface/ui_message.c
common/interfaces/user_interface/ui_multi_instruction.c
common/interfaces/user_interface/ui_scroll_page.c
common/interfaces/user_interface/ui_skip_instruction.c
common/interfaces/user_interface/ui_text_slideshow.c

The current strategy of calling `lv_obj_clean(lv_scr_act())` from inside of event handlers leads to recursive event handler calls. This is because the lv_obj_clean() does in-place object deletion hierarchically. Objects are deleted even before the event handler exits.
Additionally, the lvgl events handling appears to be unsafe for deleted object references. This means if lvgl has events E1 & E2, then calling lv_obj_clean() when E1 is being handled leads to app crashes when as the object already deleted before callback for E2 is called.
Side-effects
1. Faster transitions between two screen renders (blank screens will stay for a shorter duration).
2. Frozen screens will be show instead of blank screens (between two successive calls to `lv_task_handler`)

fix (ui): Remove recursive event callbacks

---

apps/btc_app/btc_helpers.c
apps/btc_app/btc_helpers.h
apps/btc_app/get_public_key.c
apps/btc_app/get_xpub.c
tests/common/util/xpub_verify_tests.c

Implements https://app.clickup.com/t/9002019994/PRF-4825
Add specialized API for validating derivation paths for the Bitcoin chain only. The existing API for this purpose has mixed handling for all the Bitcoin forks and Ethereum as well.

refactor: Add bitcoin derivation path guard

---

common/interfaces/user_interface/ui_address.c
common/interfaces/user_interface/ui_confirmation.c
common/interfaces/user_interface/ui_delay.c
common/interfaces/user_interface/ui_input_mnemonics.c
common/interfaces/user_interface/ui_input_text.c
common/interfaces/user_interface/ui_instruction.c
common/interfaces/user_interface/ui_joystick_training.c
common/interfaces/user_interface/ui_list.c
common/interfaces/user_interface/ui_menu.c
common/interfaces/user_interface/ui_message.c
common/interfaces/user_interface/ui_multi_instruction.c
common/interfaces/user_interface/ui_scroll_page.c
common/interfaces/user_interface/ui_skip_instruction.c
common/interfaces/user_interface/ui_text_slideshow.c

Clear screen and objects before populating any new UI component data. This will clear previously created UI components and it's objects.

refactor: Clean lvgl objs before input scr and remove duplicate comment

---

CMakeLists.txt

PB_NO_ERRMSG configuration reduces the rodata section of the nano pb library as the error messages are excluded which are not used in the X1 vault firmware project

fix: Update nano pb compile definition to exclude error messages

---

common/interfaces/user_interface/ui_instruction.c

The `lv_object` references stored in the static objects are not cleared before the next instantiation of the same UI. This can cause some logic to fail as specific decisions are made on the existence of those references.

fix (ui): Clear object references across `ui_instruction_scr` instances

---

common/interfaces/user_interface/ui_joystick_training.c

Necessary refactor to improve code readability and remove malloc

fix: Handle `LV_EVENT_CLICKED` during centre button click in joystick training ui

---

common/coin_support/wallet.h
src/card_operations/card_internal.c
src/card_operations/read_card_version.c
src/card_operations/read_card_version.h
src/constant_texts.h
src/level_four/tap_cards/controller/controller_tap_cards.h
src/level_four/tap_cards/controller/tap_one_card_controllers.c
src/level_four/tap_cards/tasks/tap_one_card_tasks.c
src/level_four/tap_cards/tasks/tasks_tap_cards.h
src/level_one/controller/controller_level_one.h
src/level_one/controller/controller_level_one_initial.c
src/level_one/tasks/tasks_level_one.h
src/level_one/tasks/tasks_level_one_initial.c
src/level_three/advanced_settings/controller/advanced_settings_controller.c
src/level_three/advanced_settings/controller/controller_advanced_settings.h
src/level_three/advanced_settings/tasks/advanced_settings_tasks.c
src/level_three/advanced_settings/tasks/tasks_advanced_settings.h
src/menu/settings_menu.c
src/settings/settings_api.h

This pull request enables viewing X1 card version. A new field `card_version` is added in `nfc_connection_data` structure, which can hold a pointer to buffer where the card version will be copied on card tap.
Fixes https://app.clickup.com/t/9002019994/PRF-4845

refactor: Port card operation to view card version and enable setting

---

src/card_operations/card_internal.c
src/card_operations/card_return_codes.h
src/wallet/reconstruct_seed_flow.c

This PR replaces `CARD_OERATION_PAIRING_REQUIRED` error code with `CARD_OPERATION_ABORT_OPERATION` since it is also a terminal case in card flows which require pairing which is configured through `init_session_keys`.

refactor: Remove 'CARD_OPERATION_PAIRING_REQUIRED' card error type

---

common/core/core_error.c
common/core/core_error_priv.h

As a part of post-abort handling device core error handler will clear the usb events for completeness of the flow exit sequence. Not doing so would result in handling of stale usb events by the application.

fix: Clear usb event on abort in flows

---

common/core/events.c
src/main.c

Implements https://app.clickup.com/t/9002019994/PRF-5022

fix: Refresh timeout counter in case joystick movement is detected

---

src/constant_texts.c
src/constant_texts.h

https://app.clickup.com/t/9002019994/PRF-6168

fix(ui): Updated text acc to suggestion

---

common/startup/application_startup.c
src/controller_main.c
src/level_four/core/controller/initial_device_provision_contoller.c
src/level_one/controller/controller_level_one_initial.c
src/level_one/tasks/tasks_level_one_initial.c
version.txt

Changes in this PR:
- USB enabled at startup in the initial app
- Joystick training and card training removed
- Handling of devices already provisioned improved to send a response to the host.
- Skipped confirmation for firmware update
- Updated and added logs for provisioning state and errors

feat(core): Removed unnecessary steps for provisoning

---

common/libraries/util/wallet_utilities.c
common/libraries/util/wallet_utilities.h
src/constant_texts.c
src/constant_texts.h
src/level_four/core/controller/verify_wallet_controller.c
src/menu/wallet_menu.c
src/wallet/reconstruct_wallet_flow.c

With this change, the wallet ID is generated and verified every time the seed/mnemonics is reconstructed.
- This would prevent wallet collision when the two shares are generated from the same mnemonics and wallet name but in different sessions.

feat(core): Verify wallet id on reconstruction

---

src/card_operations/card_fetch_share.c
src/card_operations/card_operation_typedefs.h

Part 2 of wallet verification through nonce. With this change, every time a wallet is fetched, its nonce would be verified with either a wallet from another card or a wallet already saved on the device.
Changes
- On sync flow, 2 wallets fetched would be verified for name, ID, info, and nonce between before storing the 5th share on the device.
- On any reconstruction flow, the fetched wallet would be compared with the wallet present on flash for name, id, info, and nonce.

feat(core): Verify fetched wallets

---

common/interfaces/flash_interface/flash_api.c
common/interfaces/flash_interface/flash_api.h
common/interfaces/flash_interface/flash_struct.h
common/libraries/util/utils.h
src/card_flows/card_flow_delete_wallet.c
src/card_flows/card_flow_delete_wallet.h
src/card_flows/card_flow_reconstruct_wallet.c
src/card_operations/card_delete_share.c
src/card_operations/card_fetch_share.c
src/card_operations/card_operation_typedefs.h
src/card_operations/card_write_share.c
src/settings/factory_reset.c
src/wallet/wallet_list.c
src/wallet/wallet_list.h

This PR incorporates the change where a wallet is verified before it is deleted.
These are the changes incorporated
- Record card write attempt on flash
- Fetch share (and compare with wallet intended for deletion) from the card before deleting the wallet
- Updated factory reset to include all wallets with share present on device during verification from 2 cards.

Verify wallet before delete

---

src/card_flows/card_flow_delete_wallet.c
src/card_operations/card_delete_share.c
src/card_operations/card_delete_share.h
src/card_operations/card_fetch_share.c
src/constant_texts.c

Changes added:
- Refactoring of card delete flow
- Added clearing of wallet data from memory after wallet fetch operation in card delete flow
- Treat wallet unverified as a case of wallet not found
- fix unverified error code not being returned to caller.

fix(core): Treat unverified wallets as non existant

---

CMakeLists.txt

The cmake function (`execute_process`) uses new features that were introduced in version 3.19.0 ( [Refer here](https://cmake.org/cmake/help/latest/command/execute_process.html)).

chore: Update cmake required version

---

common/interfaces/flash_interface/flash_api.c
src/settings/sync_with_cards.c
src/wallet/wallet_unlock_flow.c

The nonce value indicates if the wallet unlocking is initialized. The value 0xff...ff (32-bytes) is an indicative of uninitialized state while any other value will indicate progress of the unlocking process. Currently, The sync-wallet flow sets it to 0 which causes the unlock flow to skip card tapping step from the user.
Fixes https://app.clickup.com/t/9002019994/PRF-6961

fix (core): Set default pow-nonce to 0xff in sync wallets

---

apps/evm_family/evm_sign_msg.c

This reverts commit 27ec7018ea7255d3f19ace0698cdd544b1caea25.
Puts on hold https://app.clickup.com/t/9002019994/PRF-6382

chore: Revert "fix(evm): Sign message escape non-printable characters"

---

apps/evm_family/evm_sign_msg.c

Fixes https://app.clickup.com/t/9002019994/PRF-6382
Follow up of https://github.com/Cypherock/x1_wallet_firmware/pull/471
This reverts commit 6a3fccc2bbd344335caa5ff6e96b47ef71e53b64.

fix(evm): Sign message escape non-printable characters

---

common/libraries/util/utils.c
tests/common/util/utils_tests.c

Fixes https://app.clickup.com/t/9002019994/PRF-6382
Steps to Re-create:
1. Visit https://etherscan.io/verifiedSignatures#
2. Use "Sign Message" button
3. Use "wallet Connect" to connect the X1 Vault.
4. Write the following message
```
This message contains £ (pound) 
symbol which is not supported in X1 Vault.
```
6. Click on "Sign Message" button
7. Observe on X1 Vault screen the pound symbol (£) will be shown as hex string after this change. Prior to this, the pound symbol (£) will be completely absent as if it never existed.

chore (tests): Update escaping of non-printable characters

---

apps/evm_family/evm_contracts.c
tests/apps/evm_app/evm_txn_tests.c
tests/unit_test_lists.c
version.txt

Fixes https://app.clickup.com/t/9002019994/PRF-7131
The functions with 0 arguments result into ETH_BAD_ARGUMENTS which is incorrect. Update the parser to return OK if all of the payload is parsed irrespective of the number of arguments.

hotfix (app): Evm payload function arg parser update

---

apps/manager_app/device_authentication.c

PR: https://app.clickup.com/t/9002019994/PRF-6628

fix: Clear buffer usb for cysync mid event rejection

---

apps/inheritance_app/inheritance_auth_wallet.c

Fixes redundant pairing in `seed-based` auth flow. (making unnecessary 2nd tap )
moved pairing function inside `wallet-based` flow

fix(app): Fix redundant pairing

---

src/wallet/verify_pin_flow.c

The current flow proceeds to card tap even after user aborts PIN verification.
updated return value for `get_verify_pin()`

fix(app): End flow on early exit

---

apps/inheritance_app/inheritance_auth_wallet.c
apps/inheritance_app/inheritance_decrypt_data.c
src/card_operations/card_fetch_wallet_list.c
src/card_operations/card_internal.c
src/constant_texts.c
src/constant_texts.h

Fixes:
PRF-7597: https://app.clickup.com/t/9002019994/PRF-7597
PRF-7612: https://app.clickup.com/t/9002019994/PRF-7612
PRF-7603: https://app.clickup.com/t/9002019994/PRF-7603
PRF-7545: https://app.clickup.com/t/9002019994/PRF-7545

fix: Inheritance bugs

---

apps/xrp_app/xrp_pub_key.c

Corrects the receive confirmation text on device for xrp
Steps to Reproduce:
1. Initiate receive address for XRP
2. Check for text on device
Actual Behaviour:
- Text shown is "Receive XRP on XRP in <wallet_name>"
Expected Behaviour:
- Text should be "Receive XRP in <wallet_name>"

fix: corrected the receive text in xrp

---

apps/inheritance_app/inheritance_decrypt_data.c
src/constant_texts.h

Fix: https://app.clickup.com/t/9002019994/PRF-7746

fix(app): Pin display decryption

---

apps/inheritance_app/inheritance_decrypt_data.c
apps/inheritance_app/inheritance_encrypt_data.c

Fixes: https://app.clickup.com/t/9002019994/PRF-7750

fix: Set proper flow status in ecnryption flow

---

apps/manager_app/auth_card.c
src/settings/card_health_check.c
src/settings/view_device_info.c

Fixed some warnings for proper string formatting

Fixed some warnings

---

apps/inheritance_app/inheritance_decrypt_data.c
apps/inheritance_app/inheritance_encrypt_data.c

Instead of checking total size received from communication check the max size for Inheritance packet, because we are allocating buffer on stack

fix: Use maximum size for length check

---

apps/btc_family/btc_pub_key.c
apps/btc_family/btc_script.c
apps/btc_family/btc_txn.c
apps/btc_family/btc_txn_helpers.c
tests/apps/btc_app/btc_inputs_validator.c
tests/apps/btc_app/btc_script_tests.c
tests/apps/btc_app/btc_txn_helpers_tests.c
tests/unit_test_lists.c
version.txt

```
import { ManagerApp } from "@cypherock/sdk-app-manager";
import {
setBitcoinJSLib,
BtcApp,
IGetPublicKeyParams,
IGetXpubsParams,
ISignTxnParams
} from "@cypherock/sdk-app-btc";
import * as bitcoinJsLib from 'bitcoinjs-lib';
import hid from '@cypherock/sdk-hw-hid';
async function create_connection (){
const connection = await hid?.default.create();
const managerApp = await ManagerApp.create(connection);
setBitcoinJSLib(bitcoinJsLib);
const btcApp = await BtcApp.create(connection)
return {managerApp, btcApp}
}
create_connection().then(async ({managerApp, btcApp}) => {
// Get all wallets available on device
const allWallets = await managerApp.getWallets();
const publickey_params: IGetPublicKeyParams = {
walletId: allWallets.walletList[0].id,
derivationPath: [0x80000000+49, 0x80000000+0, …
```

feat: Add btc segwit support
