- src/level_one/tasks/tasks_level_one.c
- src/main.c
Fixes https://app.clickup.com/t/37308523/CHI-1964
> Disable abort for menus

- .github/workflows/build.yml
- .github/workflows/containerized-build.yml
- .gitmodules
- Dockerfile
- utilities/build.sh
- utilities/cmake/firmware.cmake
- utilities/script/requirements.txt
Test run result: https://github.com/ujjwal-cyph/x1_wallet_firmware/actions/runs/3043251415
> Ci cd/GitHub workflow

- common/coin_support/eth.c
- common/coin_support/eth.h
- src/level_four/core/tasks/send_transaction_tasks_eth.c
Fixes https://app.clickup.com/t/37308523/PRD-1429
Fixes https://app.clickup.com/t/37308523/CHI-2003
> Fix size parameter in eth fee calculation

- src/level_four/card_health_check/cyc_card_hc.c
Fixes https://app.clickup.com/t/37308523/CHI-2012
> Correct the acceptable card flag in card health check

- src/level_four/core/controller/sync_cards_controller.c
- src/level_four/tap_cards/controller/controller_tap_cards.c
Fixes https://app.clickup.com/t/37308523/CHI-2056
> Correct check for locked_wallet state

- common/interfaces/card_interface/nfc.c
- common/interfaces/card_interface/nfc.h
- src/level_four/tap_cards/controller/pair_card_controller.c
Fixes https://app.clickup.com/t/37308523/CHI-2030
> Show fast tap message if card absent before start of pairing

- common/libraries/util/pow_utilities.c
- common/libraries/util/pow_utilities.h
- src/level_four/core/controller/wallet_locked_controller.c
Fixes https://app.clickup.com/t/37308523/CHI-2053
> wallet unlock: Clear existing screen before rendering next one

- src/level_four/tap_cards/controller/controller_tap_cards.c
Fixes https://app.clickup.com/t/37308523/CHI-2080
> Remove unnecessary check for already tapped_card

- common/coin_support/coin_utils.c
Fixes https://app.clickup.com/t/37308523/CHI-2083
> fix: Use BTC symbol token for Bitcoin Testnet

- src/level_four/core/controller/verify_card_controller.c
https://app.clickup.com/t/37308523/CHI-2062
> added family id check before moving to pairing

- common/coin_support/coin_utils.c
- common/coin_support/coin_utils.h
- src/controller_main.c
- src/level_four/core/controller/controller_level_four.h
Fixes https://app.clickup.com/t/37308523/CHI-2065
> Extend chain id size to support larger chain IDs

- common/interfaces/desktop_app_interface/communication.c
Detects support for longer chain id
Fixes https://app.clickup.com/t/37308523/CHI-2065
> min sdk version 2.4.0

- src/level_four/core/controller/verify_card_controller.c
fixes https://app.clickup.com/t/37308523/CHI-2028
> updated order of card removal in card auth

- version.txt
Feature list
- Extend evm coin support [`#59`](https://github.com/ujjwal-cyph/x1_wallet_firmware/pull/59)
- Add command id for Coin list request [`#40`](https://github.com/ujjwal-cyph/x1_wallet_firmware/pull/40)
> Version bump v0.4.1280 (feature+2)

- common/coin_support/eth.c
- common/coin_support/eth.h
- common/libraries/util/utils.c
- common/libraries/util/utils.h
Fixes https://app.clickup.com/t/37308523/CHI-2098
> fix: Correct check on Chain ID of EVM transactions

- common/coin_support/coin_utils.c
- common/coin_support/coin_utils.h
- common/libraries/crypto/segwit_addr.c
- common/libraries/crypto/segwit_addr.h
- src/level_four/core/controller/receive_transaction_controller_eth.c
- src/level_four/core/tasks/receive_transaction_tasks_eth.c
- src/level_four/core/tasks/send_transaction_tasks_eth.c
Fixes https://app.clickup.com/t/37308523/CHI-2101
> feature: add support for bech32 addresses on Harmony

- common/startup/application_startup.c
Fixes https://app.clickup.com/t/37308523/CHI-2120
> fix: Correct the USB state on timeout

- common/coin_support/coin_utils.c
- common/coin_support/coin_utils.h
- src/level_four/core/controller/send_transaction_controller.c
- src/level_four/core/tasks/send_transaction_tasks_eth.c
- src/level_four/core/tasks/send_transaction_tasks_near.c
- src/level_four/core/tasks/send_transaction_tasks_solana.c
Fixes https://app.clickup.com/t/37308523/CHI-2125
> fix: Use 18 decimal place for EVM fee value

- src/controller_main.c
Fixes https://app.clickup.com/t/37308523/CHI-2132
> fix: Correct USB request flag (external triggered)

- src/level_four/core/tasks/verify_card_task.c
Fixes https://app.clickup.com/t/37308523/CHI-2129
> fix: Keep the screen up for user to read

- common/libraries/nanopb/pb.h
- common/libraries/nanopb/pb_common.c
- common/libraries/nanopb/pb_common.h
- common/libraries/nanopb/pb_decode.c
- common/libraries/nanopb/pb_decode.h
- common/libraries/nanopb/pb_encode.c
- common/libraries/nanopb/pb_encode.h
- utilities/cmake/firmware.cmake
Add nanopb from https://github.com/nanopb/nanopb/commit/afc499f9a410fc9bbf6c9c48cdd8d8b199d49eb4
Resolves: https://github.com/Cypherock/x1_wallet_firmware/pull/107#discussion_r1062113383
> Feat/wallet connect/nanopb

- .github/workflows/version-check.yml
This adds a pipeline check on version changes in the source.
Every PR which modifies the `version.txt` file will be checked for version downgrade. If the downgrade is detected the check pipeline will fail indicating error.
> feat (ci): Verify version change for downgrade protection

- common/coin_support/eth.c
Fixes https://app.clickup.com/t/37308523/CHI-2126
> hotfix: Decline ethereum txn with unknown payload

- common/coin_support/wallet.c
- common/coin_support/wallet.h
- common/interfaces/card_interface/nfc.c
- common/libraries/util/wallet_utilities.c
- common/libraries/util/wallet_utilities.h
Fixes https://app.clickup.com/t/37308523/CHI-2135
> feat: Add checksum calculation for card's share

- common/coin_support/wallet.c
- src/level_four/core/controller/sync_cards_controller.c
- src/level_three/add_wallet/controller/controller_new_wallet.c
- src/level_three/add_wallet/controller/controller_restore_wallet.c
Fixes https://app.clickup.com/t/37308523/CHI-2165
> Retain PIN digest till wallet verification

- common/coin_support/btc.c
- common/coin_support/btc.h
- src/level_four/core/tasks/send_transaction_tasks.c
Fixes https://app.clickup.com/t/37308523/CHI-2179
> fix: Receiver address in bitcoin forks send flow

- src/constant_texts.c
- src/level_four/core/tasks/verify_wallet_task.c
- src/level_three/add_wallet/tasks/tasks_arbitrary_data.c
- src/level_three/add_wallet/tasks/tasks_new_wallet.c
- src/level_three/add_wallet/tasks/tasks_restore_wallet.c
Fixes https://app.clickup.com/t/37308523/CHI-2180
> Add user info about view seed and PIN requirement

- common/coin_support/solana.c
https://app.clickup.com/t/37308523/CHI-2181
> fix: update Solana's derivation path verification

- version.txt
https://github.com/Cypherock/x1_wallet_firmware/pull/131
https://github.com/Cypherock/x1_wallet_firmware/pull/132
https://github.com/Cypherock/x1_wallet_firmware/pull/129
https://github.com/Cypherock/x1_wallet_firmware/pull/134
> Version bump v0.4.1801 (patch +4)

- src/controller_main.c
Fixes https://app.clickup.com/t/37308523/CHI-2177
> fix: Update user prompt for near custom account creation

- .github/workflows/publish-docs.yml
The github workflow ci will generate and publish the generated documentation for public access.
> feature (ci): Generate and publish documentation

- version.txt
https://github.com/Cypherock/x1_wallet_firmware/pull/153
https://github.com/Cypherock/x1_wallet_firmware/pull/152
https://github.com/Cypherock/x1_wallet_firmware/pull/150
> Version bump v0.4.2051 (patch + 3)

- version.txt
Increment release version to v0.4.2057 (patch + 6)
https://github.com/Cypherock/x1_wallet_firmware/pull/155
https://github.com/Cypherock/x1_wallet_firmware/pull/156
https://github.com/Cypherock/x1_wallet_firmware/pull/157
https://github.com/Cypherock/x1_wallet_firmware/pull/158
https://github.com/Cypherock/x1_wallet_firmware/pull/159
https://github.com/Cypherock/x1_wallet_firmware/pull/163
> Version bump v0.4.2057 (patch + 6)

- version.txt
https://github.com/Cypherock/x1_wallet_firmware/pull/169
> Version bump v0.4.2059 (Bugfix+1)

- version.txt
Feature improvement
- https://github.com/Cypherock/x1_wallet_firmware/pull/176
- https://github.com/Cypherock/x1_wallet_firmware/pull/181
Other improvements
- https://github.com/Cypherock/x1_wallet_firmware/pull/166
- https://github.com/Cypherock/x1_wallet_firmware/pull/171
- https://github.com/Cypherock/x1_wallet_firmware/pull/172
- https://github.com/Cypherock/x1_wallet_firmware/pull/183
> Version bump v0.4.2304 (feature + 1)

- version.txt
Fixes:
- https://github.com/Cypherock/x1_wallet_firmware/pull/190
- https://github.com/Cypherock/x1_wallet_firmware/pull/191
- https://github.com/Cypherock/x1_wallet_firmware/pull/192
> Bump Version to v0.4.2307 (bugfix +3)

- .gitattributes
Explicitly tell git to replace CRLF with LF
> chore (git): Add git attributes

- version.txt
Changes from last release
https://github.com/Cypherock/x1_wallet_firmware/pull/22
https://github.com/Cypherock/x1_wallet_firmware/pull/180
https://github.com/Cypherock/x1_wallet_firmware/pull/220
> chore(build): Updating firmware version (feat+3) to 0.4.3072

- common/core/status_api.c
- common/core/status_api.h
Implements: [PRF-4701 ](https://app.clickup.com/t/9002019994/PRF-4701)
> feat(core): Implement apis for firmware to set status packet fields

- common/interfaces/desktop_app_interface/usb_internals.c
Fixes https://app.clickup.com/t/9002019994/CHI-4826
> refactor: Use protobuf struct for status payload

- common/interfaces/user_interface/ui_list.c
- common/interfaces/user_interface/ui_scroll_page.c
- version.txt
https://app.clickup.com/t/9002019994/CHI-4871
https://app.clickup.com/t/9002019994/PRF-4692
> Fix/scr options highlighted/chi 4871

- common/interfaces/user_interface/ui_multi_instruction.c
- version.txt
https://app.clickup.com/t/9002019994/PRF-4692
https://app.clickup.com/t/9002019994/CHI-4872
> fix(ui): Ghost arrow in multi instruction scr

- src/host_interface/host_interface.c
- src/host_interface/host_interface.h
- src/manager_app/manager_app.c
- src/manager_app/manager_app.h
- src/menu/main_menu.c
- utilities/cmake/firmware/firmware.cmake
- utilities/cmake/simulator/simulator.cmake
This implements a very basic structure for the USB callback to enable invocation of applications from the host interface
> feat: Base structure for usb callback to pass control to applications

- common/interfaces/user_interface/ui_text_slideshow.c
- src/constant_texts.c
- src/constant_texts.h
- src/menu/main_menu.c
- src/menu/menu_config.c
- src/menu/menu_priv.c
- src/menu/onboarding.c
- src/menu/onboarding.h
- src/menu/onboarding_priv.h
Implements https://app.clickup.com/t/9002019994/PRF-4736
> feat: Implement onboarding ui screens and add flow on startup

- apps/manager_app/manager_app.c
- apps/manager_app/manager_app.h
- src/host_interface/host_interface.c
Implements https://app.clickup.com/t/9002019994/PRF-4740
> feat: Basic skeleton for the manager app

- apps/manager_app/get_device_info.c
- apps/manager_app/manager_api.c
- apps/manager_app/manager_api.h
- apps/manager_app/manager_app.c
- apps/manager_app/manager_app.h
- common/proto-options/manager/get_device_info.options
Fixes https://app.clickup.com/t/9002019994/PRF-4737
> feat: Add function to populate device info fields

- common/proto-options/manager/auth_device.options
- src/constant_texts.c
- src/constant_texts.h
- src/controller_main.c
- src/level_four/core/controller/device_authentication_controller.c
Implements https://app.clickup.com/t/9002019994/PRF-4709
> refactor: Use protobuf struct to perform device authentication

- apps/manager_app/device_authentication.c
- apps/manager_app/device_authentication_api.c
- apps/manager_app/device_authentication_api.h
- apps/manager_app/get_device_info.c
- apps/manager_app/manager_api.c
- apps/manager_app/manager_api.h
- apps/manager_app/manager_app.c
- apps/manager_app/manager_app.h
- common/core/flow_engine.h
- src/constant_texts.c
- src/menu/main_menu.c
- src/menu/onboarding.c
Implements device authentication flow - https://app.clickup.com/t/9002019994/PRF-4742
> feat: Implement device authentication flow

- apps/manager_app/joystick_training.c
- apps/manager_app/manager_app.c
- apps/manager_app/manager_app.h
- apps/manager_app/user_training.c
- common/interfaces/user_interface/ui_joystick_training.c
- common/interfaces/user_interface/ui_joystick_training.h
- common/proto-options/manager/train_card.options
- common/proto-options/manager/train_joystick.options
- common/proto-options/manager/train_user.options
- src/constant_texts.c
- src/constant_texts.h
Add a new UI component for joystick training actions and instructions.
Fixes https://app.clickup.com/t/9002019994/PRF-4732
> feat (ui): Add joystick training to onboarding

- apps/manager_app/device_authentication.c
- apps/manager_app/device_authentication_api.c
- apps/manager_app/joystick_training.c
Implements [PRF-4778](https://app.clickup.com/t/9002019994/PRF-4778)
> fix: Send flow completion before delay screen

- apps/manager_app/card_training.c
- apps/manager_app/manager_app_priv.h
- common/proto-options/manager/train_card.options
- src/card_operations/check_pairing.c
- src/card_operations/check_pairing.h
- src/constant_texts.h
Fixes https://app.clickup.com/t/9002019994/PRF-4760
> feat: Add card paring check in onboarding

- common/interfaces/card_interface/nfc_events.c
- src/card_operations/card_internal.c
- src/card_operations/card_operations.h
- src/card_operations/card_sign.c
- src/card_operations/card_sign.h
- src/card_operations/card_utils.c
- src/card_operations/card_utils.h
https://app.clickup.com/t/9002019994/PRF-4731
> Feat/card auth handlers/prf 4731

- apps/manager_app/auth_card.c
- apps/manager_app/card_training.c
- apps/manager_app/device_authentication.c
- apps/manager_app/get_device_info.c
- apps/manager_app/joystick_training.c
- apps/manager_app/manager_api.c
- apps/manager_app/manager_api.h
- apps/manager_app/manager_app_priv.h
- common/core/common_error.c
- common/core/common_error.h
Implements https://app.clickup.com/t/85zt3zq2f
> feat: data error handling

- apps/manager_app/auth_card.c
https://app.clickup.com/t/9002019994/PRF-4731
> Added card auth sign serial and challenge handlers PRF-4731

- apps/btc_app/btc_api.c
- apps/btc_app/btc_api.h
- apps/btc_app/btc_app.c
- apps/btc_app/btc_app.h
- apps/btc_app/btc_app_priv.h
- apps/manager_app/onboarding/onboarding_host_interface.c
- common/core/status_api.h
- common/interfaces/desktop_app_interface/usb_event.c
- src/menu/host_interface.c
- src/menu/host_interface.h
- src/menu/main_menu.c
- utilities/cmake/firmware/firmware.cmake
- utilities/cmake/simulator/simulator.cmake
Fixes https://app.clickup.com/t/9002019994/PRF-4812
Fixes https://app.clickup.com/t/9002019994/PRF-4811
> feat: Add "BTC" app skeleton

- src/card_operations/card_utils.c
- src/card_operations/write_card_share.h
- src/level_four/tap_cards/controller/write_to_cards_controller.c
Implements https://app.clickup.com/t/9002019994/PRF-4793
> refactor: Update write share to card flow using new apis

- common/core/core_error.c
- common/core/core_error.h
- common/core/core_error_priv.h
- src/controller_main.h
- src/menu/main_menu.c
https://app.clickup.com/t/9002019994/PRF-4804
> Feat/core error display/prf 4804

- src/card_operations/card_sign.c
- src/card_operations/card_utils.c
- src/card_operations/card_utils.h
- src/card_operations/read_card_share.h
- src/level_four/tap_cards/controller/card_action_controllers.c
- src/level_four/tap_cards/controller/pair_card_controller.c
- src/level_four/tap_cards/controller/write_to_cards_controller.c
Implements https://app.clickup.com/t/9002019994/PRF-4794
> refactor: Update read share from card flow using new apis

- src/card_operations/card_fetch_share.h
- src/card_operations/card_internal.c
- src/card_operations/card_internal.h
- src/card_operations/card_operations.h
- src/card_operations/card_reconstruct_wallet.h
- src/card_operations/card_utils.c
- src/card_operations/card_utils.h
- src/constant_texts.h
- src/level_four/tap_cards/controller/reconstruct_from_threshold_cards_controller.c
https://app.clickup.com/t/9002019994/PRF-4795
> refactor(nfc): Refactored nfc operation retrieve wallet

- apps/manager_app/onboarding/onboarding.c
- common/core/core_error.c
- common/core/core_error_priv.h
- common/core/events.h
- common/core/p0_events.c
- common/core/p0_events.h
- src/menu/main_menu.c
- tests/common/core/events_tests.c
- tests/p0_events/p0_events_test.c
https://app.clickup.com/t/9002019994/PRF-4803
> Update/p0 evt handling/prf 4803

- apps/manager_app/firmware_update.c
- apps/manager_app/manager_app_priv.h
- common/Firewall/sec_flash.h
- common/proto-options/common.options
- common/proto-options/manager/firmware_update.options
- src/constant_texts.h
Implements https://app.clickup.com/t/9002019994/PRF-4822
> feat: Add manager function for device firmware update confirmation

- src/card_flows/card_flow_reconstruct_wallet.c
- src/card_operations/card_fetch_share.c
- src/wallet/create_wallet_flow.c
Improves directory structure of fetch card share card operation and create wallet flow
> chore: Fix directory structure of merged flows

- apps/btc_app/get_public_key.c
- apps/btc_app/get_xpub.c
Implements https://app.clickup.com/t/9002019994/PRF-4827
> refactor: Integrate seed recreation flow in btc functions

- apps/manager_app/firmware_update.c
Incorporates suggested error code during firmware update https://github.com/Cypherock/cypherock-common/pull/23
> fix: Update error code sent during firmware update query validation

- src/constant_texts.c
- src/constant_texts.h
- src/level_two/tasks/tasks_level_two.c
- src/menu/main_menu.c
- src/menu/settings_menu.c
- src/menu/settings_menu.h
- utilities/cmake/firmware/firmware.cmake
- utilities/cmake/simulator/simulator.cmake
This pull request implements settings menu on the X1 vault device
Implements https://app.clickup.com/t/9002019994/PRF-4854
> refactor: Port settings menu

- src/level_three/advanced_settings/controller/advanced_settings_controller.c
- src/level_three/advanced_settings/tasks/advanced_settings_tasks.c
- src/settings/settings_api.h
- src/settings/view_device_info.c
Implements https://app.clickup.com/t/9002019994/PRF-4847
> refactor: Port view device info setting

- src/level_three/advanced_settings/controller/advanced_settings_controller.c
- src/level_three/advanced_settings/tasks/advanced_settings_tasks.c
- src/menu/settings_menu.c
- src/settings/settings_api.h
- src/settings/user_configuration.c
Implements https://app.clickup.com/t/9002019994/PRF-4846
> refactor: Port user configuration setting options

- src/constant_texts.c
- src/constant_texts.h
- src/level_three/advanced_settings/controller/advanced_settings_controller.c
- src/level_three/advanced_settings/tasks/advanced_settings_tasks.c
- src/menu/settings_menu.c
- src/settings/settings_api.h
- src/settings/view_device_info.c
Implements https://app.clickup.com/t/9002019994/PRF-4855
> refactor: Port regulatory info settings

- src/menu/main_menu.c
- src/menu/wallet_menu.c
- src/menu/wallet_menu.h
Adds old wallet menu navigation only.
> feat(core): Added old wallet menu

- common/interfaces/card_interface/apdu.c
- common/interfaces/card_interface/apdu.h
- common/interfaces/card_interface/nfc.c
- common/interfaces/card_interface/nfc.h
- src/card_operations/card_fetch_wallet_list.c
- src/card_operations/card_fetch_wallet_list.h
- src/card_operations/card_operations.h
- src/level_four/card_health_check/cyc_card_hc.c
- src/level_four/factory_reset/cyc_factory_reset.c
- src/level_four/tap_cards/controller/tap_one_card_controllers.c
- src/wallet/wallet_list.h
Implements https://app.clickup.com/t/9002019994/PRF-4829
> feat: Card operation to fetch wallet list from an 'X1' card

- src/constant_texts.c
- src/constant_texts.h
- src/level_four/factory_reset/cyc_factory_reset.c
- src/level_four/factory_reset/cyt_factory_reset.c
- src/menu/settings_menu.c
- src/settings/factory_reset.c
- src/settings/settings_api.h
- src/wallet/wallet_list.c
- src/wallet/wallet_list.h
Implements https://app.clickup.com/t/9002019994/PRF-4850
> refactor: Port factory reset into new architecture

- common/core/core_error.c
- common/core/core_error.h
- src/card_operations/card_fetch_share.c
- src/card_operations/card_fetch_wallet_list.c
- src/card_operations/card_fetch_wallet_list.h
- src/card_operations/card_internal.c
- src/card_operations/card_operation_typedefs.h
- src/card_operations/card_operations.h
- src/constant_texts.c
- src/constant_texts.h
- src/level_four/card_health_check/cyc_card_hc.c
- src/level_four/card_health_check/cyt_card_hc.c
- src/level_four/tap_cards/controller/controller_tap_cards.h
- src/menu/settings_menu.c
- src/settings/card_health_check.c
- src/settings/factory_reset.c
- src/settings/settings_api.h
Implements: https://app.clickup.com/t/9002019994/PRF-4848
> refactor: Port card health check in new architecture

- apps/btc_family/btc_api.c
- apps/btc_family/btc_api.h
- apps/evm_family/evm_api.c
- apps/evm_family/evm_api.h
- apps/manager_app/manager_api.c
- apps/manager_app/manager_api.h
- apps/near_app/near_api.c
Changes
- Indicate immutability of params with const
- Remove local instance from encode api
> refactor (app): Indicate immutability of params with const

- apps/btc_family/btc_pub_key.c
- apps/btc_family/btc_txn.c
- apps/btc_family/btc_xpub.c
- apps/evm_family/evm_pub_key.c
- apps/manager_app/auth_card.c
- apps/manager_app/device_authentication.c
- apps/manager_app/get_logs.c
- apps/manager_app/joystick_training.c
- apps/manager_app/onboarding/onboarding.c
- apps/near_app/near_pub_key.c
- common/core/status_api.c
- common/core/status_api.h
- src/menu/main_menu.c
- src/wallet/reconstruct_wallet_flow.c
Implements https://app.clickup.com/t/9002019994/PRF-4891
Requires: https://github.com/Cypherock/cypherock-common/pull/27
> feat: Enable flow-status sync during seed reconstruction steps

- common/interfaces/flash_interface/flash_api.c
- common/interfaces/flash_interface/flash_api.h
- src/card_operations/card_fetch_challenge.c
- src/card_operations/card_fetch_challenge.h
- src/card_operations/card_operations.h
- src/level_four/core/controller/wallet_locked_controller.c
- src/level_four/tap_cards/controller/controller_tap_cards.c
Partially implements https://app.clickup.com/t/9002019994/PRF-4859
This PR includes the Fetch challenge part of the wallet unlock process.
> refactor(nfc): Get locked wallet challenge refactored

- common/interfaces/flash_interface/flash_api.c
- common/interfaces/flash_interface/flash_api.h
- common/libraries/proof_of_work/pow.c
- common/libraries/proof_of_work/pow.h
- common/libraries/util/byte_utilities.c
- common/libraries/util/byte_utilities.h
https://app.clickup.com/t/9002019994/PRF-4859
Implements the required refactor for proof of work task handling.
> refactor(core): Refactor proof of work tasks for unlock wallet

- apps/evm_family/evm_main.c
- apps/evm_family/evm_pub_key.c
Changes included:
- Added handling for getting user verified public key
- Made code uniform with the near app in https://github.com/Cypherock/x1_wallet_firmware/pull/372
Depends on https://github.com/Cypherock/cypherock-common/pull/33
https://app.clickup.com/t/9002019994/PRF-4896
> feat: Handle request for user verified public key for evm

- src/card_operations/card_fetch_wallet_list.c
Fixes https://app.clickup.com/t/9002019994/PRF-5031
> fix: Accept 'SW_RECORD_NOT_FOUND' apdu resp while fetching wallet list

- common/startup/application_startup.c
- src/controller_main.c
- src/main.c
- src/wallet/sync_wallets_flow.c
Implements https://app.clickup.com/t/9002019994/PRF-4880
> feat: Enable startup checks for provisioning, wallet state and faults

- apps/btc_family/btc_pub_key.c
- apps/btc_family/btc_txn.c
- apps/btc_family/btc_xpub.c
- apps/evm_family/evm_pub_key.c
- apps/near_app/near_pub_key.c
- common/core/ui_core_confirm.h
- src/wallet/reconstruct_wallet_flow.c
- src/wallet/reconstruct_wallet_flow.h
- src/wallet/view_seed_flow.c
- src/wallet/wallet_list.c
- src/wallet/wallet_list.h
Implements https://app.clickup.com/t/9002019994/PRF-4892
Requires https://github.com/Cypherock/cypherock-common/pull/34
> fix: Report errors to host during wallet reconstruction flows

- apps/evm_family/eth/eth_app.h
- apps/evm_family/evm_contracts.h
- apps/evm_family/evm_helpers.c
- apps/evm_family/evm_main.c
- apps/evm_family/evm_priv.h
- apps/evm_family/evm_pub_key.c
- apps/evm_family/evm_sign_txn.c
- apps/evm_family/evm_txn_helpers.c
- apps/evm_family/evm_txn_helpers.h
- common/coin_support/coin_utils.c
- common/coin_support/coin_utils.h
- common/coin_support/eth.c
- common/coin_support/eth.h
- common/proto-options/common.options
- common/proto-options/evm/sign_txn.options
- src/constant_texts.c
- src/constant_texts.h
- src/level_four/core/controller/send_transaction_controller_eth.c
- src/level_four/core/tasks/send_transaction_tasks_eth.c
- src/level_four/core/tasks/tasks_level_four.h
- tests/apps/btc_app/btc_txn_helpers_tests.c
- tests/apps/evm_app/evm_txn_tests.c
- tests/unit_test_lists.c
- tests/unit_tests_main.c
- utilities/cmake/firmware/firmware.cmake
- utilities/cmake/simulator/simulator.cmake
Implements https://app.clickup.com/t/9002019994/PRF-4900
> refactor (app): Add evm basic transaction support

- src/constant_texts.c
Implements https://app.clickup.com/t/9002019994/PRF-6168
> fix: Update user facing error message to indicate wallet locked

- common/libraries/util/utils.c
- tests/common/util/utils_tests.c
- tests/unit_test_lists.c
- utilities/cmake/firmware/firmware.cmake
- utilities/cmake/simulator/simulator.cmake
Fixes https://app.clickup.com/t/9002019994/PRF-3020
> fix: Handle '00' padding while decoding der signature

- common/interfaces/flash_interface/flash_api.c
- src/card_operations/card_internal.c
- src/card_operations/card_unlock_wallet.h
- src/constant_texts.c
- src/constant_texts.h
- src/level_four/core/controller/wallet_locked_controller.c
- src/level_four/tap_cards/controller/controller_tap_cards.c
- src/level_three/old_wallet/controller/controller_old_wallet.c
- src/menu/wallet_menu.c
- src/wallet/wallet_unlock_flow.c
- src/wallet/wallet_unlock_flow.h
https://app.clickup.com/t/9002019994/PRF-4859
This PR implements the complete wallet unlock flow with handling of challenge fetching, unlock pow tasks, pin entry and unlock on card operation.
> refactor(flow): Unlock flow refactored

- apps/solana_app/solana_api.c
- apps/solana_app/solana_api.h
- apps/solana_app/solana_context.h
- apps/solana_app/solana_main.c
- apps/solana_app/solana_main.h
- src/menu/host_interface.c
- utilities/cmake/firmware/firmware.cmake
- utilities/cmake/simulator/simulator.cmake
https://app.clickup.com/t/9002019994/PRF-4963
> feat(app): Added skeleton for solana app proto decoding

- src/menu/host_interface.c
- src/menu/main_menu.c
- src/restricted_app/restricted_app.c
Changelist:
1. Reset core engine for handling unauthenticated device
2. Set core & app status in restricted mode
> fix: Set core & app status in restricted mode

- apps/solana_app/solana_helpers.c
- apps/solana_app/solana_helpers.h
- apps/solana_app/solana_main.c
- apps/solana_app/solana_main.h
- apps/solana_app/solana_priv.h
- apps/solana_app/solana_pub_key.c
- common/proto-options/solana/core.options
- common/proto-options/solana/get_public_keys.options
- tests/apps/solana_app/solana_add_account_tests.c
- tests/apps/solana_app/solana_txn_tests.c
- tests/common/util/xpub_verify_tests.c
- tests/unit_test_lists.c
- tests/unit_tests_main.c
- utilities/cmake/firmware/firmware.cmake
- utilities/cmake/simulator/simulator.cmake
Implements https://app.clickup.com/t/9002019994/PRF-4960
> Refactor/solana add account/prf 4960

- apps/evm_family/evm_helpers.c
- apps/evm_family/evm_helpers.h
- apps/evm_family/evm_main.c
- apps/evm_family/evm_priv.h
- apps/evm_family/evm_sign_msg.c
- common/proto-options/evm/sign_msg.options
- src/constant_texts.h
Implements https://app.clickup.com/t/9002019994/PRF-5020
> Refactor/evm sign msg/prf 5020

- common/core/events.c
- tests/apps/evm_app/evm_sign_msg_tests.c
Fixed timeout count not being reset on joystick movement
> fix(ui): Timeout not updated on joystick activity

- common/interfaces/card_interface/nfc.c
- src/app_error.h
- src/card_operations/card_sign.c
https://app.clickup.com/t/9002019994/PRF-6294
> fix(nfc): Added retry attempt for card sign exception

- src/card_operations/card_fetch_share.c
- src/card_operations/card_fetch_wallet_list.c
- src/constant_texts.c
- src/constant_texts.h
https://app.clickup.com/t/9002019994/PRF-6190
> fix(nfc): Error text updated for already tapped card

- src/settings/factory_reset.c
https://app.clickup.com/t/9002019994/PRF-6388
> fix(ui): Remove check for pairing in factory reset and clear data

- common/core/core_error.c
- common/core/core_error.h
- src/menu/create_wallet_menu.c
- src/wallet/create_new_wallet_flow.c
- src/wallet/create_new_wallet_flow.h
- src/wallet/restore_seed_phrase_flow.c
- src/wallet/restore_seed_phrase_flow.h
https://app.clickup.com/t/9002019994/PRF-6377
> fix(core): Handle wallet deletion failure for creation failure

- src/card_flows/card_flow_reconstruct_wallet.c
- src/card_flows/card_flow_reconstruct_wallet.h
- src/wallet/reconstruct_wallet_flow.c
- src/wallet/sync_wallets_flow.c
https://app.clickup.com/t/9002019994/PRF-6169
> fix(nfc): Report card error type on card errors during reconstruction

- src/wallet/reconstruct_wallet_flow.c
https://app.clickup.com/t/9002019994/PRF-6444
> fix(core): Reject callback sanity check causing unintended ui

- apps/evm_family/evm_sign_txn.c
Fixes https://app.clickup.com/t/9002019994/PRF-6403
> fix (evm): Send missing status updates to host

- apps/btc_family/btc_context.h
- tests/apps/btc_app/btc_script_tests.c
- tests/unit_test_lists.c
- tests/unit_tests_main.c
Fixes https://app.clickup.com/t/9002019994/PRF-6673
Closes https://app.clickup.com/t/9002019994/PRF-6661
> fix (app): Increase array size for hrp to 4

- common/coin_support/wallet.h
- src/level_three/add_wallet/tasks/tasks_arbitrary_data.c
- src/wallet/create_new_wallet_flow.c
- src/wallet/restore_seed_phrase_flow.c
Fixes https://app.clickup.com/t/9002019994/PRF-4057
> feat: Extend wallet name charset to alpha-numeric

- apps/manager_app/get_logs.c
Fixes https://app.clickup.com/t/9002019994/PRF-6627
> fix: Allow log fetching in restricted mode

- src/card_operations/card_internal.c
- src/card_operations/card_pair.c
- src/constant_texts.c
- src/constant_texts.h
Fixes https://app.clickup.com/t/9002019994/PRF-6831
> fix(core): Handle secure channels errors

- apps/evm_family/evm_sign_msg.c
- common/libraries/util/utils.c
- common/libraries/util/utils.h
- common/lvgl/src/lv_font/lv_symbol_def.h
- tests/common/util/utils_tests.c
- tests/unit_test_lists.c
Fixes https://app.clickup.com/t/9002019994/PRF-6382
> fix(evm): Sign message escape non-printable characters

- common/interfaces/user_interface/ui_input_text.c
- common/interfaces/user_interface/ui_input_text.h
- src/level_four/core/tasks/receive_transaction_tasks_eth.c
- src/level_four/core/tasks/receive_transaction_tasks_near.c
- src/level_four/core/tasks/receive_transaction_tasks_solana.c
- src/level_four/core/tasks/send_transaction_tasks_eth.c
- src/level_four/core/tasks/send_transaction_tasks_solana.c
- src/level_four/core/tasks/sign_message_tasks_eth.c
- src/level_four/core/tasks/verify_wallet_task.c
- src/level_four/core/tasks/wallet_locked_tasks.c
- src/level_four/tap_cards/tasks/tap_one_card_tasks.c
- src/level_three/add_wallet/tasks/tasks_arbitrary_data.c
- src/wallet/create_new_wallet_flow.c
- src/wallet/delete_wallet_flow.c
- src/wallet/reconstruct_wallet_flow.c
- src/wallet/restore_seed_phrase_flow.c
- src/wallet/sync_wallets_flow.c
- src/wallet/verify_wallet_flow.c
- src/wallet/wallet_unlock_flow.c
Fixes https://app.clickup.com/t/9002019994/PRF-4057
> fix (core): Parameterize start index for input components

- common/coin_support/eth_sign_data/abi_decode.c
BEP-20 Tokens now display checksum'd address for receiver
> Fix PRF-6996

- common/core/core_flow_init.c
Fixes https://app.clickup.com/t/9002019994/PRF-7078
> fix (app): Handle device auth state change in-between onboarding

- common/proto-options/btc/sign_txn.options
- version.txt
Fixes https://app.clickup.com/t/9002019994/PRF-7143
> hotfix (app): Increase size limit on raw txn buffer

- apps/evm_family/arbitrum/arbitrum_app.c
- apps/evm_family/avalanche/avalanche_app.c
- apps/evm_family/bsc/bsc_app.c
- apps/evm_family/eip1159.c
- apps/evm_family/eip1159.h
- apps/evm_family/eth/eth_app.c
- apps/evm_family/evm_helpers.c
- apps/evm_family/evm_helpers.h
- apps/evm_family/evm_sign_txn.c
- apps/evm_family/evm_txn_helpers.c
- apps/evm_family/evm_txn_helpers.h
- apps/evm_family/fantom/fantom_app.c
- apps/evm_family/optimism/optimism_app.c
- apps/evm_family/polygon/polygon_app.c
- tests/apps/evm_app/evm_eip1559_tests.c
- tests/apps/evm_app/evm_txn_tests.c
- tests/unit_test_lists.c
- tests/unit_tests_main.c
Closes https://app.clickup.com/t/9002019994/PRF-7159
Sample script to test the changes
```ts
import DeviceConnection from '@cypherock/sdk-hw-hid';
import { ManagerApp } from '@cypherock/sdk-app-manager';
import { setEthersLib, EvmApp } from '@cypherock/sdk-app-evm';
import { ethers } from 'ethers';
const run = async () => {
setEthersLib(ethers);
const connection = await DeviceConnection.create();
const wallet = (await (await ManagerApp.create(connection)).getWallets()).walletList[0];
const stxn = '0x02e001800a64830186a094b0ee076d7779a6ce152283f009f4c32b5f88756c6480c0';
await (await EvmApp.create(connection)).signTxn({ derivationPath: [0x8000002c, 0x8000003c, 0x80000000, 0, 0], txn: stxn, walletId: wallet.id });
connection.destroy();
};
run();
```
> feat (app): Support for eip1559 transactions

- src/constant_texts.c
update auth wallet success text
> fix(app): Auth wallet success text

- .vscode/tasks.json
- common/startup/application_startup.c
- simulator/lv_drivers/indev/keyboard.c
- simulator/lv_drivers/indev/keyboard.h
- simulator/porting/lv_port_indev.c
- tests/unit_tests_main.c
- utilities/build.sh
Add `emulate_key_press(ekp)` functionality for simulator
Update simulator build script for DEV build
Add `ekp_init` for `unit_tests`
> feat(core): Add ekp functionality in simulator

- src/card_operations/card_fetch_decrypt_data.c
- src/card_operations/card_fetch_encrypt_data.c
- src/card_operations/card_fetch_wallet_list.c
- src/card_operations/card_fetch_wallet_list.h
Fixes :
PRF#7576: https://app.clickup.com/t/9002019994/PRF-7576
PRF#7544: https://app.clickup.com/t/9002019994/PRF-7544
> fix(app): Inheritance card operations

- src/card_operations/card_pair.c
Fixes PRF-7585: https://app.clickup.com/t/9002019994/PRF-7585
> fix: Add pairing delay

- common/interfaces/desktop_app_interface/usb_internals.c
- version.txt
Check remaining size of I/O buffer before copying data in it.
> fix: Buffer overflow fix

- apps/inheritance_app/inheritance_auth_wallet.c
- apps/inheritance_app/inheritance_decrypt_data.c
- apps/inheritance_app/inheritance_encrypt_data.c
- common/core/core_error.c
- common/core/core_error.h
- src/card_operations/card_fetch_wallet_list.c
- src/wallet/verify_pin_flow.c
Fixes PRF-7603: https://app.clickup.com/t/9002019994/PRF-7603
Fixed Encryption first card tap UI bug
Added Beep sound when no wallet found
Fixed Late error popup when unpaired card tap
> fix: Add no wallet error beep sound

- apps/inheritance_app/inheritance_auth_wallet.c
- apps/inheritance_app/inheritance_decrypt_data.c
- apps/inheritance_app/inheritance_encrypt_data.c
Fix: https://app.clickup.com/t/9002019994/PRF-7603
> fix(app): Refactored display error code

- common/interfaces/card_interface/nfc.c
Reverts Cypherock/x1_wallet_firmware#637
> Revert "fix: Adds length validation in fragment apdu exchange process"
